[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqgdlltejy0akh02aay707kwaymehfvu534cggjy86tvp4ue6xzgsj5xqa2"]

[[validator_account]]
address = "tnam1q906w4yem3j4za02uq04w2mmen6w0zetf5c7kjjc"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.21.232.160:26656"

[validator_account.consensus_key]
pk = "tpknam1qrlglmu9055r0a0ghd7hclcza6vtq5ngtatz57vg44wh0kh0lphh7nvzml9"
authorization = "signam1qqsk3sgz66t56p5algwkylg3an74cqxvv8u36unlmyaxcl88lq7x4q3x6rchrcka2t3ps3vux3faqr0aargh53e0p34ed9f3949zncq26szn4e"

[validator_account.protocol_key]
pk = "tpknam1qz9vmcshm7ff7rvw7t006afx92nfe0cfm5uksp46kdk6rrel9eq36hg6gdz"
authorization = "signam1qqcl7v7rd35m4qyggcy0nsegaecwn89swqete9dszu4wnazmgg32kj5fah02f97kwgzpv869u8xtpqj7cnv306kkd6jklxgszw84ppqprwz55a"

[validator_account.tendermint_node_key]
pk = "tpknam1qz6gensrqlvy2dckez9t4qc6z58phm9r5huyd3rstprateff3jhgvjsjtfu"
authorization = "signam1qzxdptkak3t832a885y06jzgua86jy5sl98vn3zrtn8p8hdg39s5dt67nzzsnxpje54pqzfh4tanmfwkyag8rhrlm80mcdmyuhkff6c82eyjgq"

[validator_account.eth_hot_key]
pk = "tpknam1qyp8pg6xcxq2xlkllkf99h984sj7dgqf5knzgpqux8h7ne86mya3a9qpgfae0"
authorization = "signam1qymjf74lc6vrlu65g2zpxxchyrm46tg0v2mwx4hpadld78x5vvwz7dzpd2jpexpd3smaxs6jzrwcg6sfqwldzktpf6cu2awnhd5awkszqqnxyn5f"

[validator_account.eth_cold_key]
pk = "tpknam1qyppwcgdz76ekqvxuw8chcrvfar53uwg7h82g709ky405gpn5pmhw7scuadhm"
authorization = "signam1q8ee2sr9jc6dcg8lnvtnevnv9270ncemc69dnx5kvwhgu4uex9mdkl8784gqq8svqkejy63mrj45pjzyecdwvu64vd630yrmwst59egyqqq0pvzk"

[validator_account.metadata]
email = "erulbathory@gmail.com"

[validator_account.signatures]
tpknam1qqgdlltejy0akh02aay707kwaymehfvu534cggjy86tvp4ue6xzgsj5xqa2 = "signam1qqc94azmggtmmv04gf8a60a9wysxh7adzn9utthnceyx5sedwx7fq325wlt0hgx2ydnax4n8agp8w322m8uryv8nt6cuwg7vz3mkcpgp2atgjm"

[[bond]]
source = "tnam1q906w4yem3j4za02uq04w2mmen6w0zetf5c7kjjc"
validator = "tnam1q906w4yem3j4za02uq04w2mmen6w0zetf5c7kjjc"
amount = "1000000"

[bond.signatures]
tpknam1qqgdlltejy0akh02aay707kwaymehfvu534cggjy86tvp4ue6xzgsj5xqa2 = "signam1qq8skumjcu97j93e2luankkxelqezk83m67mlk09vx7906cpajlefu8kahvh87se533m8m2tsgy7qawg6eq27mw85xh4az3w0nc7e9c2j69ach"
